server:
  port: ${PUBLICATION_TEXT_SERVICE_PORT:8008}

spring:
  application:
    name: publication-text-service
  config:
    import: configserver:${CONFIG_SERVER_URL}
  profiles:
    active:
      - eureka
      - server
      - management
      - springdoc
