server:
  port: ${RATING_TEXT_SERVICE_PORT:8018}

spring:
  application:
    name: rating-text-service
  config:
    import: configserver:${CONFIG_SERVER_URL}
  profiles:
    active:
      - eureka
      - server
      - management
