server:
  port: ${CENSORING_TEXT_SERVICE_PORT:8028}

spring:
  application:
    name: censoring-text-service
  config:
    import: configserver:${CONFIG_SERVER_URL}
  profiles:
    active:
      - eureka
      - server
      - management
      - springdoc
