spring:
  config:
    import:
      - file:config/.env[.properties]
      - optional:file:config/override.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          add-label-locations: false
          search-locations:
            - './config-native'
            - './config-native/{application}'
