POST {{censoringTextServiceUrl}}/api/internal/censoring/texts
Content-Type: text/plain

This is text!

###

POST {{censoringTextServiceUrl}}/api/internal/censoring/texts
Content-Type: text/plain

This is war!

###
