server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URL}
          username: ${CONFIG_SERVER_GIT_USERNAME}
          password: ${CONFIG_SERVER_GIT_PASSWORD}
          search-paths:
            - '{application}'
        native:
          add-label-locations: false
          search-locations:
            - './config-native'
            - './config-native/{application}'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:${EUREKA_SERVER_URL}/eureka}
